### PR TITLE
Cal dav synchronizer

### PR DESCRIPTION
**Pull request by ingoratsdorf**
Adding Support for CalDAVSynchronizer

Ref: https://forge.tine20.org/view.php?id=11588

### CODE REVIEW

**Comment by ingoratsdorf** [comment]
I know what you are going to say: Squash it. Well, I tried. I am too dump for his terminal stuff. When is someone going to invent a real and proper GUI for this stuff?

**Comment by pschuele** [comment]
hi Ingo, you don't have to squash it (but I thought, github already added some gui for that?) :)

but i found one problem: https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/pull/17/files#r68745589

could you please remove that line?

thanks!

**Comment by ingoratsdorf** [comment]
Changes done, amongst a few more comment recoorections

**Comment by pschuele** [comment]
thanks.

also pushed this to gerrit (for ci testing): https://gerrit.tine20.org/tine20/3350

**Pull request merged**
