### PR TITLE
Config switch for SyncToken support

### PR DESCRIPTION
**Pull request by ingoratsdorf**
Added a config switch Tinebase_Config::WEBDAV_SYNCTOKEN_ENABLED
that can switch SyncToken support on or off in config.inc.php

### CODE REVIEW

**Comment by pschuele** [comment]
hi Ingo, thanks for the pull request (just in time for https://24pullrequests.com/ :D)
I'll put this into our gerrit for running the test suite and will give you feedback on this afterwards.

**Comment by pschuele** [comment]
hi Ingo,

some tests fail because they expect activated sync token handling.

could you switch the feature on for the tests or make the default = true?

and I created a mantis issue for this: https://forge.tine20.org/view.php?id=12452

here are the tests:

There were 3 failures:

1) Tinebase_WebDav_Plugin_SyncTokenTest::testGetSupportedReportSetForCalendarNode
Failed asserting that an array contains '{DAV:}sync-collection'.

/usr/local/share/tine20.git/tests/tine20/Tinebase/WebDav/Plugin/SyncTokenTest.php:103

2) Tinebase_WebDav_Plugin_SyncTokenTest::testPropfindSyncToken
Failed asserting that '<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"><d:response><d:href>/calendars/49e7039370dc7b71c484661f8c0aefd5a3f0d639/142/</d:href><d:propstat><d:prop><d:sync-token/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
' contains "<d:sync-token>http://tine20.net/ns/sync/5</d:sync-token></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>".

/usr/local/share/tine20.git/tests/tine20/Tinebase/WebDav/Plugin/SyncTokenTest.php:128

3) Tinebase_WebDav_Plugin_SyncTokenTest::testSyncCollection
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'HTTP/1.1 207 Multi-Status'
+'HTTP/1.1 403 Forbidden'

/usr/local/share/tine20.git/tests/tine20/Tinebase/WebDav/Plugin/SyncTokenTest.php:156

FAILURES!
Tests: 2107, Assertions: 12231, Failures: 3, Incomplete: 17, Skipped: 99.

**Comment by pschuele** [comment]
hi Ingo, i just merged your commit into the master:
https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/56f342cc62294cb6ba5a8c12a59700c8d88fe528

closing this request.

**Comment by ingoratsdorf** [comment]
Hi,
Has it been modified for the tests? I was thinking about modifying the 
tests to check for the config too, so they would not fail...

Not home at the moment, so cannot work on it.

Cheers,
Ingo

**Comment by pschuele** [comment]
hi Ingo,
I did not modify the tests. I just switched the default to "sync token activated". so you would need to deactivate the sync token feature in your config.
we also have one or two fixes for the sync token functionality in the pipeline that will be merged into master soon.

cu
Philipp

**Pull request closed without merging**
